# Generated by Django 5.2.8 on 2025-11-20 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('phong_ban', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, verbose_name='Mã NV')),
                ('nguoi_muon', models.CharField(max_length=100, verbose_name='Họ tên')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('chuc_vu', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('phong_ban', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('ly_do', models.TextField(verbose_name='Lý do mượn')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_tra_du_kien', models.DateField(verbose_name='Ngày trả dự kiến')),
                ('status', models.CharField(choices=[('draft', 'Nháp (Chờ gửi)'), ('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt (Chờ xuất kho)'), ('borrowing', 'Đang mượn'), ('returned', 'Đã trả'), ('rejected', 'Từ chối')], default='draft', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_tai_san', models.CharField(max_length=200, verbose_name='Tên tài sản')),
                ('don_vi_tinh', models.CharField(max_length=50, verbose_name='ĐVT')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('tinh_trang', models.CharField(blank=True, max_length=200, verbose_name='Tình trạng')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.loanslip')),
            ],
        ),
        migrations.CreateModel(
            name='LoanImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='loan_photos/%Y/%m/')),
                ('image_type', models.CharField(choices=[('borrow', 'Trước khi mượn'), ('return', 'Sau khi trả')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.loanslip')),
            ],
        ),
    ]
