# Generated by Django 6.0 on 2025-12-05 07:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, verbose_name='Mã NV')),
                ('nguoi_de_xuat', models.CharField(max_length=100, verbose_name='Người đề xuất')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('chuc_vu', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('phong_ban', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('ly_do', models.TextField(verbose_name='Lý do đề xuất')),
                ('nha_cung_cap', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nhà cung cấp (Nếu có)')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú chung')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp (Chờ gửi)'), ('dept_pending', 'Chờ Phụ trách bộ phận duyệt'), ('director_pending', 'Chờ Giám đốc duyệt'), ('approved', 'Đã duyệt / Hoàn tất'), ('rejected', 'Đã từ chối')], default='draft', max_length=20)),
                ('ngay_gui', models.DateTimeField(blank=True, null=True)),
                ('ngay_phu_trach_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_giam_doc_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_tu_choi', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_giam_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_giam_doc', to=settings.AUTH_USER_MODEL)),
                ('user_phu_trach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_phu_trach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang_hoa', models.CharField(max_length=255, verbose_name='Tên hàng hóa, quy cách')),
                ('don_vi_tinh', models.CharField(max_length=50, verbose_name='ĐVT')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.purchaseslip')),
            ],
        ),
    ]
