# Generated by Django 6.0 on 2025-12-05 08:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='ten_hang_hoa',
            field=models.CharField(max_length=255, verbose_name='Tên hàng hóa'),
        ),
    ]
