# Generated by Django 5.2.8 on 2025-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanitem',
            name='tinh_trang',
        ),
        migrations.AddField(
            model_name='loanitem',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú/Tình trạng'),
        ),
    ]
