# Generated by Django 6.0 on 2025-12-08 04:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_employee_alter_purchaseitem_ten_hang_hoa_loanslip_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [

        migrations.CreateModel(
            name='ExportSlip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhan_vien', models.CharField(max_length=20, verbose_name='Mã NV')),
                ('nguoi_de_xuat', models.CharField(max_length=100, verbose_name='Người đề xuất')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('chuc_vu', models.CharField(max_length=100, verbose_name='Chức vụ')),
                ('phong_ban', models.CharField(max_length=100, verbose_name='Phòng ban')),
                ('ly_do', models.TextField(verbose_name='Lý do xuất kho')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú chung')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Nháp (Chờ gửi)'), ('dept_pending', 'Chờ Trưởng phòng duyệt'), ('warehouse_pending', 'Chờ Thủ kho duyệt'), ('director_pending', 'Chờ Giám đốc duyệt'), ('completed', 'Đã xuất kho / Hoàn tất'), ('rejected', 'Đã từ chối')], default='draft', max_length=20)),
                ('ngay_gui', models.DateTimeField(blank=True, null=True)),
                ('ngay_truong_phong_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_thu_kho_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_giam_doc_duyet', models.DateTimeField(blank=True, null=True)),
                ('ngay_tu_choi', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_giam_doc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_giam_doc', to=settings.AUTH_USER_MODEL)),
                ('user_thu_kho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_thu_kho', to=settings.AUTH_USER_MODEL)),
                ('user_truong_phong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exp_truong_phong', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_hang_hoa', models.CharField(max_length=255, verbose_name='Tên tài sản/thiết bị')),
                ('don_vi_tinh', models.CharField(max_length=50, verbose_name='ĐVT')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú')),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.exportslip')),
            ],
        ),
        migrations.CreateModel(
            name='ExportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='export_photos/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='warehouse.exportslip')),
            ],
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='Hành động')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('slip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='warehouse.exportslip')),
            ],
        ),
 
    ]
