# Generated by Django 5.2.8 on 2025-11-21 01:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_remove_loanitem_tinh_trang_loanitem_ghi_chu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanslip',
            name='ngay_tra_du_kien',
        ),
        migrations.AddField(
            model_name='loanitem',
            name='ngay_muon',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mượn'),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='ngay_tra_du_kien',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày trả DK'),
        ),
    ]
