# Generated by Django 5.2.8 on 2025-11-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_remove_loanslip_ngay_tra_du_kien_loanitem_ngay_muon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanslip',
            name='ngay_tra_thuc_te',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ngày trả thực tế'),
        ),
    ]
