# Generated by Django 5.2.8 on 2025-11-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_loanslip_ngay_tra_thuc_te'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanslip',
            name='status',
            field=models.CharField(choices=[('draft', 'Nháp (Chờ gửi)'), ('dept_pending', 'Chờ Trưởng phòng duyệt'), ('director_pending', 'Chờ Giám đốc duyệt'), ('warehouse_pending', 'Chờ Kho xuất hàng'), ('borrowing', 'Đang mượn (Đã xuất kho)'), ('returning', 'Chờ xác nhận trả'), ('returned', 'Đã trả / Hoàn tất'), ('rejected', 'Đã từ chối')], default='draft', max_length=20),
        ),
    ]
