# Generated by Django 5.2.8 on 2025-11-24 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_alter_loanslip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanitem',
            name='tinh_trang',
            field=models.CharField(choices=[('binh_thuong', 'Bình thường'), ('hu_hong', 'Hư hỏng'), ('khac', 'Khác (Ghi chú thêm)')], default='binh_thuong', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AddField(
            model_name='loanitem',
            name='tinh_trang_khac',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chi tiết (nếu chọn Khác)'),
        ),
        migrations.AlterField(
            model_name='loanitem',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ghi chú chung'),
        ),
    ]
