# Generated by Django 5.2.8 on 2025-11-24 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_loanitem_tinh_trang_loanitem_tinh_trang_khac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanslip',
            name='ngay_muon',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ngày mượn'),
        ),
    ]
