# Generated by Django 5.2.8 on 2025-11-24 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0007_loanslip_ngay_muon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanslip',
            name='ngay_muon',
        ),
    ]
