# Generated by Django 5.2.8 on 2025-11-25 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0008_remove_loanslip_ngay_muon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='loanslip',
            name='user_giam_doc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyet_gd', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanslip',
            name='user_nguoi_tra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nguoi_tra', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanslip',
            name='user_thu_kho_nhap',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyet_kho_nhap', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanslip',
            name='user_thu_kho_xuat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyet_kho_xuat', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loanslip',
            name='user_truong_phong',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duyet_tp', to=settings.AUTH_USER_MODEL),
        ),
    ]
